name: "chand"
username: "Publisethi"
bio: "everybody will be dancing if we are doing it right :: bits goa :: jiohotstar"
location: "Bangalore, India"
calLink: "cal.com/chand/15min"
joinedDate: "August 1995"
headerImage: "/images/header.png"
profilePic: "/images/profile_pic.png"
verified: true
